name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-26.04-arm, macos-latest, macos-26-intel]
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: make # assumes GNUMake
      - name: Test
        run: make test-all
      - name: Setup
        run: sudo make install
      - name: Run in PATH
        run: chibi-scheme r7rs-tests.scm
        working-directory: tests
  windows-build:
    name: windows-build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            gcc
            plocate
      - name: Build
        run: msys2 -c "make PLATFORM=msys"
      - name: Find msys-2.0.dll
        run: msys2 -c "updatedb && locate msys-2.0.dll"
      - name: Install NSIS
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis
      - name: Create installer
        run: C:\Users\runneradmin\scoop\shims\makensis.exe windows_installer.nsi
      - uses: actions/upload-artifact@v7
        with:
          path: setup_chibi-scheme.exe
          archive: false
