name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-26.04-arm, macos-latest, macos-26-intel]
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: make # assumes GNUMake
      - name: Test
        run: make test-all
      - name: Setup
        run: sudo make install
      - name: Run in PATH
        run: chibi-scheme r7rs-tests.scm
        working-directory: tests
  msys2-build:
    name: msys2-build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            gcc
      - name: Build
        run: msys2 -c "make PLATFORM=msys"
      - name: Tests
        run: msys2 -c "make PLATFORM=msys test"
  windows-installer:
    name: windows-installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            gcc
            mingw-w64-x86_64-nsis
            findutils
      - name: Build
        run: msys2 -c "make PLATFORM=msys"
      - name: Tests
        run: msys2 -c "make PLATFORM=msys test"
      - env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        run: |
          find "$env:MSYS2_LOCATION" -name msys-2.0.dll
          #cp $(find $env:MSYS2_LOCATION -name msys-2.0.dll) .
          #find $env:MSYS2_LOCATION -name msys-gcc_s-seh-1.dll
          #cp $(find $env:MSYS2_LOCATION -name msys-gcc_s-seh-1.dll) .
          #/mingw64/bin/makensis installer.nsi
      - uses: actions/upload-artifact@v7
        with:
          name: setup_chibi-scheme.exe
          path: setup_chibi-scheme.exe
