name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-26.04-arm, macos-latest, macos-26-intel]
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: make # assumes GNUMake
      - name: Test
        run: make test-all
      - name: Setup
        run: sudo make install
      - name: Run in PATH
        run: chibi-scheme r7rs-tests.scm
        working-directory: tests
  windows-build:
    name: windows-build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cygwin/cygwin-install-action@v6
          with:
            packages: gcc
      - name: Build
        run: make
        working-directory: tests
  windows-installer:
    name: windows-installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install NSIS
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis
      - name: Build
        run: make && tree .
      - name: Print NSIS version
        run: makensis -VERSION
      - name: Print NSIS compile flags
        run: makensis -HDRINFO
